travis:
  secure:
    BINSTAR_TOKEN: UKNGnbFzvfNnNaENrdmwE9oxoLiaUVdATh8AiezGWHmEAJVw6tYPGtVJknS73tlhwc12lg2Qx+F7WIeqZfs3wTK20F+KIrrVNnN5FBLwzX9oYpgmpcDexVdT9Ib8s5j9rezw1c2w05uT3iG27T2nXBNpuqFxAFzvCQeXF76HtdV1SV7M0SM7S+YAuhDZcFuw6CMh64E+pO5x+vffONVEuUnA51HaBGZa9SKjdpWX1yW6XI4Zm5wmMTb/q7RZLWK4hpPOJV68EPNjLIvgrClYfkmtG52JEDP+8Ohl85vpyJjBjrNNBdqozscFYy+a0i18UXcbXN1sgncqp5QqiwEZeZ1N1YhNTuo0N+ud8bjMIVbeypnRInCEckEKifsGaA6+/CGoXfs3wBb3mX7S3HIe/yybz3SlBUYzJbksOWC0NA+PeBTVkhQDKb8VoC/7Kt+UAu4yQGPVvF9jouWJO4ULKdN6+sRMleO7Vi0NzvTy6BbnrmYPAWKJc4BZk/aackM3o0heb0uQjc/IkGy42gcTSyWNmlxxfomZpbibK8Hq4E4gI6HieDKhA+Jvqjkvv72c6/2lcNQ5tiHHwb1iMdro7Er6muVgxtsluISGqHQWc8M+TsUgrvlQYog3HV9A9g2QlKgpOOiCR5COOjktziIIzKzR+J2ox9Uw5opjBUNsRqQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
